kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: fence-controller
  name: fence-controller
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: standalone-fence-controller
    spec:
      containers:
      - name: standalone-fence-controller
        image: "quay.io/bronhaim/standalone-fence-controller:latest"
        imagePullPolicy: Always
      - name: kubectl-proxy
        image: docker.io/palmstonegames/kubectl-proxy
        imagePullPolicy: IfNotPresent
      serviceAccountName: fence-controller
