kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fence-controller
  namespace: default
rules:
  # Allow controller to do everything on nodefence objs
- apiGroups: [""]
  resources: ["nodefences.ha.k8s.io"]
  verbs: ["get", "update", "delete", "create"]
  # Allow controller to create new config map.
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fence-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fence-controller
subjects:
- kind: ServiceAccount
  name: fence-controller
  namespace: default
