apiVersion: v1
kind: List
items:

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-cluster-config
   namespace: default
  data:
   config.properties: |-
    grace_timeout=10
    giveup_retries=5

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-config-kubernetes-minion-group-9ssp
   namespace: default
  data:
   config.properties: |-
    node_name=kubernetes-minion-group-9ssp
    isolation=cordon
    power_management=gcloud-reset-inst
    recovery=uncordon

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-gcloud-reset-inst-kubernetes-minion-group-9ssp
   namespace: default
  data:
   method.properties: |
          agent_name=gcloud-reset-inst
          zone=us-east1-b
          project=kube-cluster-fence-poc

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-cordon-kubernetes-minion-group-9ssp
   namespace: default
  data:
   method.properties: |
          agent_name=cordon

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-uncordon-kubernetes-minion-group-9ssp
   namespace: default
  data:
   method.properties: |
          agent_name=uncordon