apiVersion: v1
kind: List
items:

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-template-fc-switch-brocade
   namespace: default
  data:
   template.properties: |-
          name=fc_switch_brocade
          agent_name=fence_brocade
          ipaddr=192.168.1.2
          password=brocade_password
          username=brocade_admin

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-template-apc-pdu
   namespace: default
  data:
   template.properties: |-
          name=apc_pdu
          agent_name=fence_apc_snmp
          must_sucess=yes
          ipaddr=192.168.1.3
          password=apc_password
          username=apc_admin

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-template-fence-apc-snmp
   namespace: default
  data:
   method.properties: |-
     agent_name=fence_apc_snmp
     ip=rack05-pdu01-lab4.tlv.redhat.com
     password=qum5net
     username=emesika

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-template-eaton-pdu
   namespace: default
  data:
   template.properties: |-
          name=eaton_pdu
          agent_name=fence_eaton_snmp
          must_sucess=yes
          ipaddr=192.168.1.4
          password=eaton_password
          username=eaton_admin
          snmp-priv-prot=AES
          snmp-priv-passwd=eaton_snmp_passwd
          snmp-sec-level=authPriv
          inet4-only=true